#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-machinist_2.12
Version  : 0.6.1
Release  : 2
URL      : https://github.com/typelevel/machinist/archive/v0.6.1.tar.gz
Source0  : https://github.com/typelevel/machinist/archive/v0.6.1.tar.gz
Source1  : https://repo1.maven.org/maven2/org/typelevel/machinist_2.12/0.6.1/machinist_2.12-0.6.1.jar
Source2  : https://repo1.maven.org/maven2/org/typelevel/machinist_2.12/0.6.1/machinist_2.12-0.6.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-machinist_2.12-data = %{version}-%{release}

%description
## Machinist
> "Generic types and overloaded operators would let a user code up all
> of these, and in such a way that they would look in all ways just
> like types that are built in. They would let users grow the Java
> programming language in a smooth and clean way."
> -- Guy Steele, "Growing a Language"

%package data
Summary: data components for the mvn-machinist_2.12 package.
Group: Data

%description data
data components for the mvn-machinist_2.12 package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/typelevel/machinist_2.12/0.6.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/typelevel/machinist_2.12/0.6.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/typelevel/machinist_2.12/0.6.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/typelevel/machinist_2.12/0.6.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/typelevel/machinist_2.12/0.6.1/machinist_2.12-0.6.1.jar
/usr/share/java/.m2/repository/org/typelevel/machinist_2.12/0.6.1/machinist_2.12-0.6.1.pom
